Repository paldo-tourism/paldo-tourism, pull requests merged in 2024-05, with the labels that each got.

#39 [FE] 결제 및 결제 완료 페이지 제작
  src/main/java/com/estsoft/paldotourism/controller/PaymentPageController.java
  src/main/resources/static/css/payment/payment.css
  src/main/resources/static/css/payment/paymentComplete.css
  src/main/resources/templates/payment/payment.html
  src/main/resources/templates/payment/paymentComplete.html
Labels: 🌈feature, 🌸frontend

#38 [ALL] pw - detail, myPage
  src/main/java/com/estsoft/paldotourism/config/SecurityConfig.java
  src/main/java/com/estsoft/paldotourism/controller/UserController.java
  src/main/java/com/estsoft/paldotourism/controller/UserPageController.java
  src/main/java/com/estsoft/paldotourism/dto/user/PasswordChangeDto.java
  src/main/java/com/estsoft/paldotourism/repository/UserRepository.java
  src/main/java/com/estsoft/paldotourism/service/UserService.java
  src/main/resources/static/js/user/forgot-pw.js
  src/main/resources/static/js/user/myPage/myPage-edit.js
  src/main/resources/static/js/user/signup.js
  src/main/resources/templates/user/forgot-pw.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/myPage/myPage-edit.html
  src/main/resources/templates/user/myPage/myPage-main.html
  src/main/resources/templates/user/myPage/myPage.html
  src/main/resources/templates/user/signup.html
Labels: 🔔all

#44 [All] 좌석선택 FE 및 onClick 로직 구현
  src/main/java/com/estsoft/paldotourism/controller/MailController.java
  src/main/resources/static/css/reservation/seat.css
  src/main/resources/static/js/reservation/seatSelect.js
  src/main/resources/templates/reservation/seatSelect.html
Labels: 🔔all, 🌈feature

#45 [BE] 문의게시판 CRUD 권한
  src/main/java/com/estsoft/paldotourism/config/SecurityConfig.java
  src/main/java/com/estsoft/paldotourism/controller/ArticleController.java
  src/main/java/com/estsoft/paldotourism/dto/qna/article/ArticleRequestDTO.java
  src/main/java/com/estsoft/paldotourism/dto/qna/article/ArticleResponseDTO.java
  src/main/java/com/estsoft/paldotourism/entity/Article.java
  src/main/java/com/estsoft/paldotourism/service/ArticleService.java
  src/main/resources/static/css/article/articleList.css
  src/main/resources/static/js/article/pagination.js
  src/main/resources/templates/article/articleLayout.html
  src/main/resources/templates/article/list.html
  src/main/resources/templates/article/update.html
  src/main/resources/templates/article/write.html
  src/test/java/com/estsoft/paldotourism/repository/ArticleServiceTest.java
Labels: 🍀backend, 🌈feature, 🌸frontend

#47 [ALL] delete user + a
  src/main/java/com/estsoft/paldotourism/config/CustomAuthenticationFailureHandler.java
  src/main/java/com/estsoft/paldotourism/config/SecurityConfig.java
  src/main/java/com/estsoft/paldotourism/controller/UserController.java
  src/main/java/com/estsoft/paldotourism/controller/UserPageController.java
  src/main/java/com/estsoft/paldotourism/service/UserService.java
  src/main/resources/static/css/user/login.css
  src/main/resources/static/js/header.js
  src/main/resources/static/js/user/myPage/myPage-edit.js
  src/main/resources/static/js/user/signup.js
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/myPage/myPage-edit.html
  src/main/resources/templates/user/myPage/myPage-main.html
Labels: 🍀backend, 🌈feature, 🌸frontend

#50 [ALL] 메인화면 로직 수정 및 예외 처리
  src/main/java/com/estsoft/paldotourism/controller/LikeController.java
  src/main/java/com/estsoft/paldotourism/dto/bus/BusInfoFindResponseDto.java
  src/main/java/com/estsoft/paldotourism/dto/openapi/OpenApiResponseItems.java
  src/main/java/com/estsoft/paldotourism/exception/ErrorForm.java
  src/main/java/com/estsoft/paldotourism/exception/GlobalExceptionHandler.java
  src/main/java/com/estsoft/paldotourism/exception/bus/TerminalNotFoundException.java
  src/main/java/com/estsoft/paldotourism/exception/openapi/BusRouteNotFoundException.java
  src/main/java/com/estsoft/paldotourism/exception/openapi/UrlNotValidException.java
  src/main/java/com/estsoft/paldotourism/service/BusApiService.java
  src/main/java/com/estsoft/paldotourism/service/BusTerminalService.java
  src/main/java/com/estsoft/paldotourism/service/LikesService.java
  src/main/resources/static/css/reservation/timeTable.css
  src/main/resources/static/img/empty-heart.png
  src/main/resources/static/img/red-heart.png
  src/main/resources/static/js/index.js
  src/main/resources/static/js/indexModal.js
  src/main/resources/static/js/reservation/timeTable.js
  src/main/resources/templates/reservation/timeTable.html
Labels: 🐞bug, 🍀backend, 🌸frontend

#52 [BE] 예약&결제 API 구현
  src/main/java/com/estsoft/paldotourism/controller/PaymentHistoryController.java
  src/main/java/com/estsoft/paldotourism/controller/PaymentPageController.java
  src/main/java/com/estsoft/paldotourism/controller/ReservationController.java
  src/main/java/com/estsoft/paldotourism/dto/reservation/ReservationRequestDto.java
  src/main/java/com/estsoft/paldotourism/entity/Reservation.java
  src/main/java/com/estsoft/paldotourism/entity/Seat.java
  src/main/java/com/estsoft/paldotourism/entity/Status.java
  src/main/java/com/estsoft/paldotourism/repository/ReservationRepository.java
  src/main/java/com/estsoft/paldotourism/repository/SeatRepository.java
  src/main/java/com/estsoft/paldotourism/service/PaymentHistoryService.java
  src/main/java/com/estsoft/paldotourism/service/ReservationService.java
Labels: 🍀backend, 💾db, 🌈feature

#48 [ALL] 예약페이지로 선택된 좌석 리스트 전송
  src/main/resources/static/css/reservation/seat.css
  src/main/resources/static/js/reservation/seatSelect.js
  src/main/resources/templates/reservation/seatSelect.html
Labels: 🔔all, 🌈feature

#49 [BE] 글쓰기 오류 수정
  src/main/java/com/estsoft/paldotourism/controller/ArticleController.java
  src/main/java/com/estsoft/paldotourism/controller/CommentController.java
  src/main/java/com/estsoft/paldotourism/dto/qna/article/ArticleRequestDTO.java
  src/main/java/com/estsoft/paldotourism/dto/qna/article/PageResponseDTO.java
  src/main/java/com/estsoft/paldotourism/dto/qna/comment/CommentRequestDTO.java
  src/main/java/com/estsoft/paldotourism/dto/qna/comment/CommentResponseDTO.java
  src/main/java/com/estsoft/paldotourism/entity/Comment.java
  src/main/java/com/estsoft/paldotourism/repository/CommentRepository.java
  src/main/java/com/estsoft/paldotourism/service/ArticleService.java
  src/main/java/com/estsoft/paldotourism/service/CommentService.java
  src/main/resources/static/css/article/articleList.css
  src/main/resources/static/css/article/articleRead.css
  src/main/resources/static/js/article/articleRead.js
  src/main/resources/static/js/article/pagination.js
  src/main/resources/templates/article/list.html
  src/main/resources/templates/article/readNew.html
  src/main/resources/templates/article/readOld.html
  src/test/java/com/estsoft/paldotourism/repository/ArticleServiceTest.java
Labels: 🍀backend

#54 [FE] ai추천페이지 프론트구현
  src/main/resources/static/css/ai/aiRecommend.css
  src/main/resources/static/js/ai/aiRecommend.js
  src/main/resources/templates/ai/aiRecommend.html
Labels: 🌈feature, 🌸frontend

#56 [FE] 사용자 선택항목 추가
  src/main/resources/static/css/ai/aiRecommend.css
  src/main/resources/templates/ai/aiRecommend.html
Labels: 🌈feature, 🌸frontend

#61 [ALL] 예약&결제 api 보완 및 프론트 수정
  src/main/java/com/estsoft/paldotourism/controller/PaymentHistoryController.java
  src/main/java/com/estsoft/paldotourism/controller/PaymentPageController.java
  src/main/java/com/estsoft/paldotourism/entity/PaymentHistory.java
  src/main/java/com/estsoft/paldotourism/entity/PaymentStatus.java
  src/main/java/com/estsoft/paldotourism/repository/SeatRepository.java
  src/main/java/com/estsoft/paldotourism/service/PaymentHistoryService.java
  src/main/java/com/estsoft/paldotourism/service/ReservationService.java
  src/main/resources/static/js/payment/payment.js
  src/main/resources/templates/payment/payment.html
  src/main/resources/templates/payment/paymentComplete.html
Labels: 🔔all, 💾db, 🌈feature

#62 [BE] 결제 완료시 문자 전송 기능 구현
  build.gradle
  src/main/java/com/estsoft/paldotourism/controller/MessageController.java
Labels: 🍀backend, 🌈feature

#66 [BE] alan api 로직 구현
  build.gradle
  src/main/java/com/estsoft/paldotourism/controller/AlanController.java
  src/main/java/com/estsoft/paldotourism/dto/AlanDto.java
  src/main/java/com/estsoft/paldotourism/service/AlanService.java
  src/main/resources/templates/ai/aiRecommend.html
Labels: 🍀backend, 🌈feature

#63 [ALL] 문의게시판 댓글 CRUD
  src/main/java/com/estsoft/paldotourism/controller/ArticleController.java
  src/main/java/com/estsoft/paldotourism/controller/CommentController.java
  src/main/java/com/estsoft/paldotourism/dto/qna/article/ArticleResponseDTO.java
  src/main/java/com/estsoft/paldotourism/dto/qna/article/PageResponseDTO.java
  src/main/java/com/estsoft/paldotourism/dto/qna/comment/CommentRequestDTO.java
  src/main/java/com/estsoft/paldotourism/dto/qna/comment/CommentResponseDTO.java
  src/main/java/com/estsoft/paldotourism/entity/Article.java
  src/main/java/com/estsoft/paldotourism/entity/Comment.java
  src/main/java/com/estsoft/paldotourism/repository/CommentRepository.java
  src/main/java/com/estsoft/paldotourism/service/ArticleService.java
  src/main/java/com/estsoft/paldotourism/service/CommentService.java
  src/main/resources/static/css/article/article.css
  src/main/resources/static/css/article/articleRead.css
  src/main/resources/static/css/article/articleWrite.css
  src/main/resources/static/js/article/articleRead.js
  src/main/resources/templates/article/articleLayout.html
  src/main/resources/templates/article/list.html
  src/main/resources/templates/article/readNew.html
  src/main/resources/templates/article/update.html
  src/main/resources/templates/article/write.html
  src/test/java/com/estsoft/paldotourism/service/ArticleServiceTest.java
  src/test/java/com/estsoft/paldotourism/service/CommentServiceTest.java
Labels: 🍀backend, 🌈feature, 🌸frontend

#69 [BE] 답변 가공
  src/main/java/com/estsoft/paldotourism/dto/AlanDto.java
  src/main/java/com/estsoft/paldotourism/service/AlanService.java
Labels: 🍀backend, 🌈feature

#75 [ALL] alan 관련 기타 작업
  src/main/java/com/estsoft/paldotourism/controller/AlanController.java
  src/main/java/com/estsoft/paldotourism/controller/CommentController.java
  src/main/java/com/estsoft/paldotourism/dto/AlanDto.java
  src/main/java/com/estsoft/paldotourism/service/AlanService.java
  src/main/resources/static/css/ai/aiAnswer.css
  src/main/resources/static/js/ai/aiAnswer.js
  src/main/resources/static/js/ai/aiRecommend.js
  src/main/resources/templates/ai/aiAnswer.html
  src/main/resources/templates/mail.html
Labels: 🔔all, 🌈feature

#77 [BE] 메인화면테스트코드
  src/main/java/com/estsoft/paldotourism/PaldoTourismApplication.java
  src/main/java/com/estsoft/paldotourism/config/JpaAuditingConfig.java
  src/main/java/com/estsoft/paldotourism/controller/BusApiController.java
  src/main/java/com/estsoft/paldotourism/exception/GlobalExceptionHandler.java
  src/main/java/com/estsoft/paldotourism/exception/bus/BusNotFoundException.java
  src/main/java/com/estsoft/paldotourism/exception/likes/NotLikedYetException.java
  src/main/java/com/estsoft/paldotourism/service/BusApiService.java
  src/main/java/com/estsoft/paldotourism/service/LikesService.java
  src/main/java/com/estsoft/paldotourism/service/SeatService.java
  src/main/resources/data.sql
  src/main/resources/static/js/index.js
  src/main/resources/templates/error/404error.html
  src/main/resources/templates/index.html
  src/test/java/com/estsoft/paldotourism/repository/BusRepositoryTest.java
  src/test/java/com/estsoft/paldotourism/repository/BusTerminalRepositoryTest.java
  src/test/java/com/estsoft/paldotourism/repository/LikesRepositoryTest.java
  src/test/java/com/estsoft/paldotourism/repository/SeatRepositoryTest.java
  src/test/java/com/estsoft/paldotourism/service/BusApiServiceTest.java
  src/test/java/com/estsoft/paldotourism/service/BusTerminalServiceTest.java
  src/test/java/com/estsoft/paldotourism/service/LikesServiceTest.java
  src/test/java/com/estsoft/paldotourism/service/SeatServiceTest.java
Labels: ✅test

#74 [BE]myPage-reservation,likes rendering
  src/main/java/com/estsoft/paldotourism/config/SecurityConfig.java
  src/main/java/com/estsoft/paldotourism/controller/CommentController.java
  src/main/java/com/estsoft/paldotourism/controller/UserPageController.java
  src/main/java/com/estsoft/paldotourism/entity/Likes.java
  src/main/java/com/estsoft/paldotourism/repository/LikesRepository.java
  src/main/java/com/estsoft/paldotourism/service/LikesService.java
  src/main/resources/static/css/user/myPage.css
  src/main/resources/static/js/user/myPage/myPage-likes.js
  src/main/resources/static/js/user/myPage/myPage.js
  src/main/resources/templates/payment/paymentComplete.html
  src/main/resources/templates/user/myPage/myPage-likes.html
  src/main/resources/templates/user/myPage/myPage-main.html
Labels: 🍀backend

#76 [BE] 예약 API 보완 및 스케줄링 추가 및 버그 수정
  src/main/java/com/estsoft/paldotourism/PaldoTourismApplication.java
  src/main/java/com/estsoft/paldotourism/controller/PaymentHistoryController.java
  src/main/java/com/estsoft/paldotourism/controller/PaymentPageController.java
  src/main/java/com/estsoft/paldotourism/entity/PaymentHistory.java
  src/main/java/com/estsoft/paldotourism/repository/SeatRepository.java
  src/main/java/com/estsoft/paldotourism/service/ReservationService.java
  src/main/resources/static/js/payment/payment.js
  src/main/resources/templates/payment/paymentComplete.html
Labels: 🍀backend, 💾db, 🌈feature

#79 [BE] fix 문의게시판 관리자 비밀글 조회 및 상태 추가
  src/main/java/com/estsoft/paldotourism/controller/ArticleController.java
  src/main/java/com/estsoft/paldotourism/dto/qna/article/ArticleResponseDTO.java
  src/main/java/com/estsoft/paldotourism/entity/Article.java
  src/main/java/com/estsoft/paldotourism/entity/Category.java
  src/main/java/com/estsoft/paldotourism/service/ArticleService.java
  src/main/resources/templates/article/articleLayout.html
  src/main/resources/templates/article/list.html
  src/main/resources/templates/article/readNew.html
Labels: 🍀backend

#82 [ALL] 머지 후 실행 오류 해결
  src/main/java/com/estsoft/paldotourism/PaldoTourismApplication.java
  src/main/java/com/estsoft/paldotourism/repository/ArticleRepository.java
  src/main/java/com/estsoft/paldotourism/repository/BusRepository.java
  src/main/java/com/estsoft/paldotourism/repository/CommentRepository.java
  src/main/java/com/estsoft/paldotourism/repository/LikesRepository.java
  src/main/java/com/estsoft/paldotourism/repository/PaymentHistoryRepository.java
  src/main/java/com/estsoft/paldotourism/repository/ReservationRepository.java
  src/main/java/com/estsoft/paldotourism/repository/UserRepository.java
Labels: 🐞bug, 🔔all, ⚙️setting

#83 [ALL] 화면전환로직 구현
  src/main/java/com/estsoft/paldotourism/controller/AlanController.java
  src/main/resources/static/css/reservation/seat.css
  src/main/resources/static/js/index.js
  src/main/resources/templates/index.html
  src/main/resources/templates/reservation/main.html
Labels: 🔔all, 🌈feature

#86 [BE] 내 예약 페이지에 예약 중인 예약 제외하고 표시
  src/main/java/com/estsoft/paldotourism/PaldoTourismApplication.java
  src/main/java/com/estsoft/paldotourism/config/JpaAuditingConfig.java
  src/main/java/com/estsoft/paldotourism/controller/UserPageController.java
  src/main/java/com/estsoft/paldotourism/repository/ReservationRepository.java
  src/main/java/com/estsoft/paldotourism/service/ReservationService.java
Labels: 🍀backend, 💾db, 🌈feature

#88 [BE] 미로그인 상태로 /myPage 접근시 처리
  src/main/java/com/estsoft/paldotourism/config/SecurityConfig.java
  src/main/java/com/estsoft/paldotourism/controller/ErrorPageController.java
  src/main/resources/templates/user/login-result-test.html
  src/main/resources/templates/user/login.html
Labels: 🐞bug, 🍀backend

#89 [BE] findSeatDetails 메소드 반환형태 변경
  src/main/java/com/estsoft/paldotourism/repository/ReservationRepository.java
  src/main/java/com/estsoft/paldotourism/service/MailService.java
Labels: 🍀backend

#91 [ALL] 좌석 테이블 예약 테이블 연결
  src/main/java/com/estsoft/paldotourism/service/PaymentHistoryService.java
  src/main/java/com/estsoft/paldotourism/service/ReservationService.java
  src/main/resources/static/js/payment/payment.js
  src/main/resources/templates/payment/payment.html
  src/main/resources/templates/payment/paymentComplete.html
Labels: 🔔all, 💾db, 🌈feature

#92 [ALL] 잔버그수정
  src/main/java/com/estsoft/paldotourism/controller/BusApiController.java
  src/main/java/com/estsoft/paldotourism/controller/ReservationController.java
  src/main/java/com/estsoft/paldotourism/dto/bus/BusInfoFindRequestDto.java
  src/main/java/com/estsoft/paldotourism/exception/GlobalExceptionHandler.java
  src/main/java/com/estsoft/paldotourism/exception/request/InvalidBusGradeRequestException.java
  src/main/java/com/estsoft/paldotourism/exception/request/InvalidDateRequestException.java
  src/main/java/com/estsoft/paldotourism/exception/reservation/ReservationNotAllowedException.java
  src/main/java/com/estsoft/paldotourism/service/BusApiService.java
  src/main/java/com/estsoft/paldotourism/service/SeatService.java
  src/main/resources/static/js/reservation/seatSelect.js
  src/main/resources/static/js/user/myPage/myPage-likes.js
  src/main/resources/templates/payment/payment.html
  src/main/resources/templates/payment/paymentComplete.html
  src/main/resources/templates/reservation/timeTable.html
Labels: 🐞bug, 🍀backend

#93 [BE] ai 기타작업
  src/main/java/com/estsoft/paldotourism/controller/MailController.java
  src/main/java/com/estsoft/paldotourism/dto/MailDto.java
  src/main/java/com/estsoft/paldotourism/repository/ReservationRepository.java
  src/main/java/com/estsoft/paldotourism/repository/SeatRepository.java
  src/main/java/com/estsoft/paldotourism/service/MailService.java
  src/main/resources/static/js/payment/payment.js
Labels: 🍀backend, 🌈feature

#94 [RELEASE] ci/cd 파이프라인 구축
  .github/application-template.yml
  appspec.yml
  scripts/deploy.sh
  src/main/resources/data.sql
Labels: ⚙️setting, 🎈release

#95 [RELEASE ] Git Actions: workflow에 ci/cd용 yml 생성
  .github/workflows/gradle.yml
Labels: ⚙️setting, 🎈release

#98 [FE] 좌석 번호 표시 개선
  src/main/resources/static/css/payment/payment.css
  src/main/resources/static/css/payment/paymentComplete.css
  src/main/resources/templates/payment/payment.html
  src/main/resources/templates/payment/paymentComplete.html
Labels: 🌸frontend

#104 [BE] 컨트롤러 반환 경로 수정
  src/main/java/com/estsoft/paldotourism/controller/PaymentPageController.java
Labels: 🐞bug, 🍀backend

#101 [BE] return 경로 형식 변경
  src/main/java/com/estsoft/paldotourism/controller/AlanController.java
Labels: 🐞bug

#108 [Docs] create_readme
  README.md
Labels: 📝docs

#109 [docs] update_readme
  README.md
  assets/ai-view.png
  assets/login-view.png
  assets/main-view.png
  assets/mypage-likes-view.png
  assets/mypage-reservation-view.png
  assets/payment-complete-view.png
  assets/payment-view.png
  assets/qna-board-view.png
  assets/qna-read-view.png
  assets/qna-write-view.png
  assets/seat-select-view.png
  assets/singup-view.png
  assets/time-table-view.png
Labels: 📝docs

#112 [docs] update_readme
  README.md
  assets/archi.png
  assets/signup-view.png
Labels: 📝docs

#116 [BE] 문의게시판 배포 후 접근 가능한 경로로 수정
  src/main/java/com/estsoft/paldotourism/controller/ArticleController.java
  src/main/resources/templates/article/articleLayout.html
  src/main/resources/templates/article/list.html
  src/main/resources/templates/article/readNew.html
  src/main/resources/templates/article/update.html
  src/main/resources/templates/article/write.html
Labels: 🐞bug

#118 [ALL] 작은 기능들 개선 및 오류 해결
  src/main/java/com/estsoft/paldotourism/controller/MessageController.java
  src/main/java/com/estsoft/paldotourism/controller/ReservationController.java
  src/main/java/com/estsoft/paldotourism/controller/UserPageController.java
  src/main/java/com/estsoft/paldotourism/dto/user/MyPageReservationDto.java
  src/main/java/com/estsoft/paldotourism/entity/Reservation.java
  src/main/resources/static/js/payment/payment.js
  src/main/resources/templates/payment/payment.html
  src/main/resources/templates/user/myPage/myPage-main.html
Labels: 🐞bug, 🔔all, 🌈feature

#123 [BE] 예약 변경 오류 해결
  src/main/resources/static/js/user/myPage/myPage.js
Labels: 🐞bug, 🍀backend

#125 [BE] 서비스에 있는 api 컨트롤러로 빼기
  src/main/java/com/estsoft/paldotourism/controller/ReservationController.java
  src/main/java/com/estsoft/paldotourism/service/BusApiService.java
  src/main/java/com/estsoft/paldotourism/service/ReservationService.java
Labels: 🍀backend

#132 [FE] 좌석, 버튼 스타일 변경
  src/main/resources/static/css/reservation/seat.css
Labels: 🌈feature, 🌸frontend

#134 [FE] 결제창에서 5분 지났을 때 결제 안되게 하기
  src/main/java/com/estsoft/paldotourism/service/ReservationService.java
  src/main/resources/static/js/payment/payment.js
Labels: 🌈feature, 🌸frontend

#135 [FE] 프론트 수정
  src/main/java/com/estsoft/paldotourism/service/CommentService.java
  src/main/resources/static/css/ai/aiAnswer.css
  src/main/resources/static/css/ai/aiRecommend.css
  src/main/resources/static/css/article/articleList.css
  src/main/resources/static/css/article/articleRead.css
  src/main/resources/static/css/article/articleWrite.css
  src/main/resources/static/css/index.css
  src/main/resources/static/css/indexModal.css
  src/main/resources/static/css/layout/header.css
  src/main/resources/static/css/payment/payment.css
  src/main/resources/static/css/payment/paymentComplete.css
  src/main/resources/static/css/reservation/timeTable.css
  src/main/resources/static/css/user/login.css
  src/main/resources/static/css/user/myPage.css
  src/main/resources/static/css/user/signup.css
  src/main/resources/templates/article/articleLayout.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/payment/payment.html
  src/main/resources/templates/payment/paymentComplete.html
  src/main/resources/templates/reservation/timeTable.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/signup.html
Labels: 🌸frontend

#138 [FE] 프론트 누락된 파일 추가
  src/main/resources/static/css/user/edit.css
  src/main/resources/templates/user/myPage/myPage-edit-old.html
  src/main/resources/templates/user/myPage/myPage-edit.html
Labels: 🌸frontend

#139 [fix] 메일에 잘못된 예매 내용 수정
  src/main/java/com/estsoft/paldotourism/repository/ReservationRepository.java
  src/main/java/com/estsoft/paldotourism/service/MailService.java
Labels: 🐞bug, 🍀backend

#146 [BE] 회원 탈퇴 로직 개선
  src/main/java/com/estsoft/paldotourism/repository/LikesRepository.java
  src/main/java/com/estsoft/paldotourism/service/UserService.java
Labels: 🐞bug, 🍀backend

#147 [BE] 수정 페이지 오류 수정
  src/main/java/com/estsoft/paldotourism/controller/ArticleController.java
  src/main/java/com/estsoft/paldotourism/dto/qna/article/ArticleRequestDTO.java
  src/main/java/com/estsoft/paldotourism/dto/qna/article/ArticleResponseDTO.java
  src/main/java/com/estsoft/paldotourism/entity/Article.java
  src/main/java/com/estsoft/paldotourism/repository/ArticleRepository.java
  src/main/java/com/estsoft/paldotourism/service/ArticleService.java
  src/main/resources/templates/article/update.html
  src/main/resources/templates/article/write.html
  src/test/java/com/estsoft/paldotourism/service/CommentServiceTest.java
Labels: 🍀backend

#148 [ALL] 배포
  src/main/java/com/estsoft/paldotourism/controller/ArticleController.java
  src/main/java/com/estsoft/paldotourism/dto/qna/article/ArticleRequestDTO.java
  src/main/java/com/estsoft/paldotourism/dto/qna/article/ArticleResponseDTO.java
  src/main/java/com/estsoft/paldotourism/entity/Article.java
  src/main/java/com/estsoft/paldotourism/repository/ArticleRepository.java
  src/main/java/com/estsoft/paldotourism/repository/LikesRepository.java
  src/main/java/com/estsoft/paldotourism/service/ArticleService.java
  src/main/java/com/estsoft/paldotourism/service/UserService.java
  src/main/resources/templates/article/update.html
  src/main/resources/templates/article/write.html
  src/test/java/com/estsoft/paldotourism/service/CommentServiceTest.java
Labels: 🔔all
