Repository paldo-tourism/paldo-tourism, pull requests merged in 2024-04, with the labels that each got.

#1 [ALL] 프로젝트 기본 세팅
  build.gradle
  src/main/java/com/estsoft/paldotourism/config/Temporary.java
  src/main/java/com/estsoft/paldotourism/controller/Temporary.java
  src/main/java/com/estsoft/paldotourism/dto/Temporary.java
  src/main/java/com/estsoft/paldotourism/entity/Temporary.java
  src/main/java/com/estsoft/paldotourism/repository/Temporary.java
  src/main/java/com/estsoft/paldotourism/service/Temporary.java
Labels: ⚙️setting

#16 [FE] timeTable화면 구성 header 제작
  src/main/resources/static/css/layout/header.css
  src/main/resources/static/css/reservation/timeTable.css
  src/main/resources/static/img/paldo_temporary_logo.png
  src/main/resources/static/js/header.js
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/reservation/timeTable.html
Labels: 🌈feature, 🌸frontend

#18 [BE] 메일 발송 api 로직 구현
  build.gradle
  src/main/java/com/estsoft/paldotourism/controller/MailController.java
  src/main/java/com/estsoft/paldotourism/dto/MailDto.java
  src/main/java/com/estsoft/paldotourism/service/MailService.java
  src/main/resources/templates/mail.html
Labels: 🍀backend, 🌈feature

#20 [BE] 로그인 기능 구현
  src/main/java/com/estsoft/paldotourism/config/SecurityConfig.java
  src/main/java/com/estsoft/paldotourism/controller/UserController.java
  src/main/java/com/estsoft/paldotourism/controller/UserPageController.java
  src/main/java/com/estsoft/paldotourism/dto/user/AddUserRequestDto.java
  src/main/java/com/estsoft/paldotourism/service/UserService.java
  src/main/resources/static/js/user/login.js
  src/main/resources/static/js/user/signup.js
  src/main/resources/templates/user/login-result-test.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/signUp.html
  src/main/resources/templates/user/signup.html
Labels: 🍀backend, 🌈feature

#23 [BE] login, signup-detail
  src/main/java/com/estsoft/paldotourism/config/SecurityConfig.java
  src/main/java/com/estsoft/paldotourism/controller/UserController.java
  src/main/java/com/estsoft/paldotourism/controller/UserPageController.java
  src/main/java/com/estsoft/paldotourism/entity/User.java
  src/main/java/com/estsoft/paldotourism/repository/UserRepository.java
  src/main/java/com/estsoft/paldotourism/service/Temporary.java
  src/main/java/com/estsoft/paldotourism/service/UserDetailService.java
  src/main/java/com/estsoft/paldotourism/service/UserService.java
  src/main/resources/static/js/user/signup.js
  src/main/resources/templates/user/login-result-test.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/signup.html
Labels: 🍀backend

#24 [BE] 문의게시판 CRUD 구현
  src/main/java/com/estsoft/paldotourism/controller/ArticleController.java
  src/main/java/com/estsoft/paldotourism/dto/qna/article/ArticleRequestDTO.java
  src/main/java/com/estsoft/paldotourism/dto/qna/article/ArticleResponseDTO.java
  src/main/java/com/estsoft/paldotourism/dto/qna/article/PageResponseDTO.java
  src/main/java/com/estsoft/paldotourism/dto/qna/comment/CommentRequestDTO.java
  src/main/java/com/estsoft/paldotourism/dto/qna/comment/CommentResponseDTO.java
  src/main/java/com/estsoft/paldotourism/entity/Article.java
  src/main/java/com/estsoft/paldotourism/entity/Comment.java
  src/main/java/com/estsoft/paldotourism/repository/ArticleRepository.java
  src/main/java/com/estsoft/paldotourism/service/ArticleService.java
  src/main/resources/templates/article/article.html
  src/main/resources/templates/article/list.html
  src/main/resources/templates/article/read.html
  src/main/resources/templates/article/update.html
  src/main/resources/templates/article/write.html
  src/test/java/com/estsoft/paldotourism/repository/ArticleServiceTest.java
Labels: 🍀backend

#25 [BE] 안쓰는 import 제거
  src/main/java/com/estsoft/paldotourism/controller/ArticleController.java
Labels: 🍀backend

#26 [BE] 문의게시판 CRUD 병합
  src/main/java/com/estsoft/paldotourism/controller/ArticleController.java
  src/main/java/com/estsoft/paldotourism/dto/qna/article/ArticleRequestDTO.java
  src/main/java/com/estsoft/paldotourism/dto/qna/article/ArticleResponseDTO.java
  src/main/java/com/estsoft/paldotourism/dto/qna/article/PageResponseDTO.java
  src/main/java/com/estsoft/paldotourism/dto/qna/comment/CommentRequestDTO.java
  src/main/java/com/estsoft/paldotourism/dto/qna/comment/CommentResponseDTO.java
  src/main/java/com/estsoft/paldotourism/entity/Article.java
  src/main/java/com/estsoft/paldotourism/entity/Comment.java
  src/main/java/com/estsoft/paldotourism/repository/ArticleRepository.java
  src/main/java/com/estsoft/paldotourism/service/ArticleService.java
  src/main/resources/templates/article/article.html
  src/main/resources/templates/article/list.html
  src/main/resources/templates/article/read.html
  src/main/resources/templates/article/update.html
  src/main/resources/templates/article/write.html
  src/test/java/com/estsoft/paldotourism/repository/ArticleServiceTest.java
Labels: 🍀backend, 🌈feature

#31 [BE] dto 관련 setter 구현
  src/main/java/com/estsoft/paldotourism/dto/MailDto.java
  src/main/java/com/estsoft/paldotourism/repository/ReservationRepository.java
  src/main/java/com/estsoft/paldotourism/service/MailService.java
Labels: 🍀backend

#29 [BE]api조회데이터db에save
  build.gradle
  src/main/java/com/estsoft/paldotourism/controller/BusApiController.java
  src/main/java/com/estsoft/paldotourism/controller/ReservationController.java
  src/main/java/com/estsoft/paldotourism/dto/bus/BusInfoFindRequestDto.java
  src/main/java/com/estsoft/paldotourism/dto/bus/BusInfoFindResponseDto.java
  src/main/java/com/estsoft/paldotourism/dto/openapi/OpenApiResponse.java
  src/main/java/com/estsoft/paldotourism/dto/openapi/OpenApiResponseBody.java
  src/main/java/com/estsoft/paldotourism/dto/openapi/OpenApiResponseBusItem.java
  src/main/java/com/estsoft/paldotourism/dto/openapi/OpenApiResponseHeader.java
  src/main/java/com/estsoft/paldotourism/dto/openapi/OpenApiResponseItems.java
  src/main/java/com/estsoft/paldotourism/dto/openapi/OpenApiResult.java
  src/main/java/com/estsoft/paldotourism/entity/Bus.java
  src/main/java/com/estsoft/paldotourism/entity/BusTerminal.java
  src/main/java/com/estsoft/paldotourism/entity/Seat.java
  src/main/java/com/estsoft/paldotourism/entity/SeatStatus.java
  src/main/java/com/estsoft/paldotourism/repository/BusRepository.java
  src/main/java/com/estsoft/paldotourism/repository/BusTerminalRepository.java
  src/main/java/com/estsoft/paldotourism/repository/SeatRepository.java
  src/main/java/com/estsoft/paldotourism/service/BusApiService.java
  src/main/java/com/estsoft/paldotourism/service/ReservationService.java
Labels: 🍀backend, 🌈feature

#33 [BE] 결제 API 적용 및 결제 테이블 CRUD 구현, 간단한 테스트 HTML 생성 추가
  .gitignore
  build.gradle
  src/main/java/com/estsoft/paldotourism/controller/PaymentHistoryController.java
  src/main/java/com/estsoft/paldotourism/entity/PaymentHistory.java
  src/main/java/com/estsoft/paldotourism/service/PaymentHistoryService.java
  src/main/resources/templates/payment/payment.html
Labels: 🍀backend, 🌈feature, ⚙️setting

#32 [BE] 문의게시판 검색 추가
  src/main/java/com/estsoft/paldotourism/controller/ArticleController.java
  src/main/java/com/estsoft/paldotourism/dto/qna/article/ArticleRequestDTO.java
  src/main/java/com/estsoft/paldotourism/dto/qna/article/PageResponseDTO.java
  src/main/java/com/estsoft/paldotourism/entity/Article.java
  src/main/java/com/estsoft/paldotourism/repository/ArticleRepository.java
  src/main/java/com/estsoft/paldotourism/service/ArticleService.java
  src/main/resources/templates/article/list.html
  src/main/resources/templates/article/read.html
  src/main/resources/templates/article/write.html
Labels: 🍀backend, 🌈feature
